### ISSUE TITLE
No Proc or mem stats available in topbeat dashboard

### ISSUE THREAD

**Issue by shaunrampersad** [elastic/packetbeat-dashboards#37]
Hi
These dashboards are great but some aren't displaying correctly.

My Setup:
Topbeat-1.0.0
Elastic 2.0
Kibana 4.2.0

The cpu graphs are blank. If I look at the visualization and associated saved search, they all return blank even though there are results available in the Discovery search with no filters enabled

I've modified the search query for "Proc Stats" and "Processes" from "type: proc" to "type: proc*"

I'm new to ELK stack, so this might not be the most optimal solution.

Regards
Shaun

**Comment by stan** [comment]
Types for those were changed from `proc` to `process`

See https://github.com/elastic/topbeat/commit/c64c139618986c43441421ee5e195807ea38741b

**Comment by shaunrampersad** [comment]
Changed the Search to "type: process" which fixes it. 
NB: the default install of beats-dashboard has "type: proc" as a filter item and not "type: process"

**Comment by tsg** [comment]
Thanks for reporting, what happened is that we forgot to merge the 1.0.0 branch into master. Now the changes should be in master as well.

Note that we generally recommend downloading the distribution from e.g. http://download.elastic.co/beats/dashboards/beats-dashboards-1.0.0.tar.gz rather than using master. Those "builds" are better tested with the corresponding release.
