### ISSUE TITLE
Allow for custom kibana index

### ISSUE THREAD

**Issue by shaunrampersad** [elastic/packetbeat-dashboards#38]
Hi

By default the load.sh will upload dashboards to http://localhost:9200/.kibana. 

In the case of kibana installations which use custom indices, it might be worthwhile making the index a variable within the script so that the dashboard can be uploaded to multiple kibana installs. 

E.G:
./load.sh http://localhost:9200 .kibana_env1
./load.sh http://localhost:9200 .kibana_env2

Its not a major issue but more a nice to have. For now I'm editing the load.sh and replacing .kibana with other names and then loading.

Thanks
shaun

**Comment by ruflin** [comment]
@shaunrampersad Thanks for bringing it up. In case you built a configurable solution for yourself, feel free to open a PR with it.

**Comment by shaunrampersad** [comment]
@ruflin I've submitted a PR. Might not be the best solution but its what I've changed on my side to get it working

**Comment by ruflin** [comment]
@shaunrampersad Thanks. Looks like we have now two proposals for the same thing https://github.com/elastic/beats-dashboards/pull/40 We will have a look at both.

**Comment by monicasarbu** [comment]
@shaunrampersad @lmangani  Thank you for submitting a PR to solve this issue. To fulfill all requests, I added support for command arguments to the load script:

<pre>
  ./load.sh -url http://localhost:9200 -user admin -index .kenv1
Options:
  -h | -help
    Print the help menu.
  -l | -url
    Elasticseacrh URL. By default is http://localhost:9200.
  -u | -user
    Username to connect to Elasticsearch. By default no username is used.
  -i | -index
    Kibana index pattern where to save the dashboards, visualizations, index patterns. By default is .kibana.
</pre>

**Comment by monicasarbu** [comment]
Here is the related pull request: https://github.com/elastic/beats-dashboards/pull/42

**Comment by monicasarbu** [comment]
Fixed by #42.

**Comment by arnelcapendit** [comment]
Hello Guys, 
I will seek some expert advise here. Cause currently we are working on the customization of our Kibana tool and we are trying to by pass the Kibana default index which was the 'kibana.index' and experimenting to alter it by creating another index. We want to have custom index so that all visualizations and dashboards will not go through the default one. Is that possible? We tried to modified some codes on kibana.yml and index.js files. See below.

//kibana.yml
//We tried to create another index aside from kibana.index but it's failing.
#kibana.index: ".kibana" 
 //Ex. #kibana.index: "test" , #kibana.index: ".kibana_test", etc

//index.js
//We tried to create another variable for kibanaIndex
var kibanaIndex = server.config().get('kibana.index');
//Ex. var kibanaIndex = 'test', var testIndex = '.kibana', etc.

We tried to test different scenario by manipulating on those two points. Are we doing it right?
If you have a documentation and process on how to properly customize the kibana index, it will very a appreciated.

Thanks in advance. :)

**Comment by ruflin** [comment]
@arnelcapendit For questions please use https://discuss.elastic.co/c/beats
